# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Jeffrey Lin
tagline:             ' Bolg'
description:         ''
url:                 https://jeffreylinweiyou.github.io/blog/
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Jeffrey Lin
  url:               Jeffrey_Lin@asus.com
  email:             Jeffrey_Lin@asus.com

# Custom vars
version:             1.0.0
